name: CI de Pruebas y Cobertura JaCoCo

on:
  push:
    branches: [ main ] # Disparar en cada push a la rama principal
  pull_request:
    branches: [ main ] # Disparar al crear Pull Requests

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Ejecutar en una máquina virtual Linux

    steps:
    - name: Clonar el Código
      uses: actions/checkout@v4
      
    - name: Configurar Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven 

    - name: Ejecutar Pruebas y Generar Reporte JaCoCo
      # El comando 'mvn package' fuerza la generacion del reporte JaCoCo en target/site/jacoco/
      run: |
        mvn test
        mvn package
        
    - name: Subir el Reporte HTML como Artefacto
      # Esto crea el archivo ZIP descargable que necesitas
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report # Nombre del archivo ZIP a descargar
        path: target/site/jacoco/